spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
management:
  otlp:
    metrics:
      export:
        enabled: false
# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: configserver:http://config-server:8888
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        enabled: true
        url: http://my-collector-collector.observability.svc.cluster.local:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://my-collector-collector.observability.svc.cluster.local:4318/v1/traces
      export:
        step: 10s # Export interval set to 10 seconds
  tracing:
    sampling:
      probability: 1.0
