server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          default-label: main
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}
management:
  otlp:
    metrics:
      export:
        enabled: false
---
spring:
  config:
    activate:
      on-profile: kubernetes
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        enabled: true
        url: http://my-collector-collector.observability.svc.cluster.local:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://my-collector-collector.observability.svc.cluster.local:4318/v1/traces
      export:
        step: 10s # Export interval set to 10 seconds
  tracing:
    sampling:
      probability: 1.0
