apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinic-chart.fullname" . }}
  labels:
    {{- include "petclinic-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "petclinic-chart.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "petclinic-chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "petclinic-chart.serviceAccountName" . | trim }}
      containers:
        - name: {{ include "petclinic-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 1 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 0 }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 3 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 1 }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 0 }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 3 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
